<a href="https://colab.research.google.com/github/2303A52269/Generative-AI/blob/main/2303A52269_week8_ASS8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report


In [3]:
data = pd.read_csv("/content/winequality-red.csv")  # Update with actual path if needed

In [4]:
X = data.drop("quality", axis=1)
y = data["quality"]


In [5]:
y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])  # Adjust for classification


In [6]:
y = pd.get_dummies(y)  # One-hot encoding for ANN classification


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [9]:
model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(25, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(y.shape[1], activation='softmax')  # Output layer
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])


In [11]:
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))


Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.3153 - loss: 1.1100 - val_accuracy: 0.3313 - val_loss: 1.1088
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3124 - loss: 1.1096 - val_accuracy: 0.3313 - val_loss: 1.1088
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2959 - loss: 1.1119 - val_accuracy: 0.3313 - val_loss: 1.1087
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2997 - loss: 1.1116 - val_accuracy: 0.3344 - val_loss: 1.1086
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3224 - loss: 1.1102 - val_accuracy: 0.3344 - val_loss: 1.1085
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3107 - loss: 1.1133 - val_accuracy: 0.3344 - val_loss: 1.1085
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3048 - loss: 1.1107 - val_accuracy: 0.3313 - val_loss: 1.1084
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3117 - loss: 1.1086 - val_accuracy: 0.3313 - 

In [12]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3523 - loss: 1.0986  
Test Accuracy: 0.34687501192092896


In [13]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test.values, axis=1)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step  


In [14]:
conf_matrix = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_true, y_pred_classes))


Confusion Matrix:
 [[28 77 36]
 [24 69 39]
 [ 2 31 14]]
Classification Report:
               precision    recall  f1-score   support

           0       0.52      0.20      0.29       141
           1       0.39      0.52      0.45       132
           2       0.16      0.30      0.21        47

    accuracy                           0.35       320
   macro avg       0.36      0.34      0.31       320
weighted avg       0.41      0.35      0.34       320



In [15]:
model.save("wine_quality_model.h5")

In [16]:
def load_model():
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    return loaded_model


In [17]:
loaded_model = load_model()
predictions = loaded_model.predict(X_test[:5])
print("Sample Predictions:", np.argmax(predictions, axis=1))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step
Sample Predictions: [2 1 0 1 2]
